services:
  master:
    build: .
    env_file: .env
    environment:
      - SERVICE_TYPE=master
    ports:
     - "8000:${MASTER_PORT}"
  secondary:
    build: .
    env_file: .env
    environment:
      - SERVICE_TYPE=secondary
    deploy:
      replicas: 1
    ports:
     - "8001-8001:${SECONDARY_PORT}"
    depends_on:
      - master
  delayed-secondary:
    build: .
    env_file: .env
    environment:
      - SERVICE_TYPE=secondary
      - DELAY=10,40
    deploy:
      replicas: 2
    ports:
      - "8004-8005:${SECONDARY_PORT}"
    depends_on:
      - master