services:
  master:
    build: .
    env_file: .env
    environment:
      - SERVICE_TYPE=master
    ports:
     - "8000:${MASTER_PORT}"
  secondary:
    build: .
    env_file: .env
    environment:
      - SERVICE_TYPE=slave
    deploy:
      replicas: 3
    ports:
     - "8001-8003:${SECONDARY_PORT}"
    depends_on:
      - master
  delayed-secondary:
    build: .
    env_file: .env
    environment:
      - SERVICE_TYPE=slave
      - DELAY=20
    deploy:
      replicas: 1
    ports:
      - "8004:${SECONDARY_PORT}"
    depends_on:
      - master